### ISSUE TITLE
Trouble getting dependencies to Install

### ISSUE THREAD

**Issue by niftynei** [imightbeamy/buzzerbot9000#1]
I'm getting an error setting up the NPM dependencies -- the error log says there's an issue parsing the json.  I'm running npm v2.1.4.  See stack trace below.

```
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'install', '--verbose' ]
npm info using npm@2.1.4
npm info using node@v0.11.11
npm ERR! install Couldn't read dependencies
npm verb stack Error: Failed to parse json
npm verb stack Unexpected token }
npm verb stack     at parseError (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:378:25)
npm verb stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:85:51)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:59:33
npm verb stack     at evalmachine.<anonymous>:258:14
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm verb stack     at Object.oncomplete (evalmachine.<anonymous>:97:15)
npm verb cwd /Users/lisaneigut/Knaps/buzzerbot9000
npm ERR! Darwin 13.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! node v0.11.11
npm ERR! npm  v2.1.4
npm ERR! file /Users/lisaneigut/Knaps/buzzerbot9000/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token }
npm ERR! File: /Users/lisaneigut/Knaps/buzzerbot9000/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lisaneigut/Knaps/buzzerbot9000/npm-debug.log
```

**Comment by imightbeamy** [comment]
There was an out of place comma, should be good now!

https://github.com/imightbeamy/buzzerbot9000/commit/3b0fff5caa964d17436f89f644a0f96019acc7cd

**Comment by niftynei** [comment]
Sweet!  I'll re-pull.  It looks like there's another issue with express installing now (running it on my raspi now, may be a different error?)

```
npm WARN buzzerbot9000@0.0.0 dependencies field should be hash of <name>:<version-range> pairs
npm http GET https://registry.npmjs.org/express

npm ERR! Error: failed to fetch from registry: express
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/buzzerbot9000/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.6.11+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
npm ERR! cwd /home/pi/buzzerbot9000
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: express
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/buzzerbot9000/npm-debug.log
npm not ok
```

**Comment by niftynei** [comment]
Ok, yeah worked fine on my macintosh. Not sure what the raspi error is.  Thanks @imightbeamy!
