### ISSUE TITLE
`node test.js` fails with Error: ENOENT, no such file or directory 'towns.json'

### ISSUE THREAD

**Issue by knocte** [imightbeamy/buzzerbot9000#4]
Following the instructions from here (https://www.twilio.com/blog/2014/05/making-your-apartment-buzzer-party-friendly-with-raspberry-pi-and-twilio.html) if I run `node test.js` I get this error:

```
$ node test.js 

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'towns.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.HomeTown (/home/pi/Documents/Code/buzzerbot9000/lib/validators/home_town.js:13:38)
    at Object.<anonymous> (/home/pi/Documents/Code/buzzerbot9000/test.js:6:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by knocte** [comment]
This seems to be a regression introduced in https://github.com/imightbeamy/buzzerbot9000/commit/b69687af0ed18071a904fee19d47ce87102e3f36 but if I revert that commit, I get another error, which is:

```
$ node test.js 

/home/pi/Documents/Code/buzzerbot9000/test.js:7
ht.isValid("hello", "123-124-2341");
   ^
TypeError: Object #<Object> has no method 'isValid'
    at Object.<anonymous> (/home/pi/Documents/Code/buzzerbot9000/test.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by knocte** [comment]
If I rename "isValid" to "validate" in test.js, I get another error, which is:

```
$ node test.js 

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'secrets'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.GoogleAddressApi.getAddress (/home/pi/Documents/Code/buzzerbot9000/lib/validators/google_request.js:8:20)
    at Object.Validator.validate (/home/pi/Documents/Code/buzzerbot9000/lib/validators/home_town.js:18:26)
    at Object.<anonymous> (/home/pi/Documents/Code/buzzerbot9000/test.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

See? This is why I'm not a fan of node.js (or any dynamically-typed language for that matter), because stuff breaks easily without the developer noticing. If you had a semantic compiler (like statically-typed languages have), then you wouldn't have introduced this regressions ;-) (end-of-rant).
